-- PostgreSQL/Supabase production schema (condensed V1)
create extension if not exists pgcrypto;
create table companies(id uuid primary key default gen_random_uuid(), name text not null, vat text unique not null, sector text, city text, province text, ships boolean default false, verified boolean default false, created_at timestamptz default now());
create table profiles(id uuid primary key references auth.users(id) on delete cascade, company_id uuid references companies(id) on delete cascade, name text, phone text, role text not null default 'member' check(role in ('member','seller','buyer','admin')), created_at timestamptz default now());
create table categories(id uuid primary key default gen_random_uuid(), name text unique not null, slug text unique not null);
create table listings(id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id) on delete cascade, category_id uuid references categories(id), title text not null, description text, quantity numeric not null check(quantity>=0), unit text not null default 'pz', condition text, location text, ships boolean default false, unit_price numeric(12,2) not null check(unit_price>=0), min_qty numeric default 1, full_lot_price numeric(12,2), accepts_offers boolean default true, liquidate_fast boolean default false, status text default 'active' check(status in ('draft','active','paused','sold','deleted')), views bigint default 0, created_at timestamptz default now());
create table product_images(id uuid primary key default gen_random_uuid(), listing_id uuid references listings(id) on delete cascade, storage_path text not null, sort_order int default 0);
create table pricing_tiers(id uuid primary key default gen_random_uuid(), listing_id uuid references listings(id) on delete cascade, min_qty numeric not null, unit_price numeric(12,2) not null);
create table offers(id uuid primary key default gen_random_uuid(), listing_id uuid references listings(id), buyer_company_id uuid references companies(id), seller_company_id uuid references companies(id), quantity numeric not null, price numeric(12,2) not null, message text, status text default 'pending', created_at timestamptz default now());
create table offer_events(id uuid primary key default gen_random_uuid(), offer_id uuid references offers(id) on delete cascade, actor_company_id uuid references companies(id), status text not null, quantity numeric, price numeric(12,2), created_at timestamptz default now());
create table favorites(profile_id uuid references profiles(id) on delete cascade, listing_id uuid references listings(id) on delete cascade, primary key(profile_id,listing_id));
create table channels(id text primary key, name text not null, type text, country text, status text default 'inactive', api_available boolean default false, feed_available boolean default false, auto_publish boolean default false, inventory_sync boolean default false, config jsonb default '{}'::jsonb);
create table channel_listings(id uuid primary key default gen_random_uuid(), channel_id text references channels(id), listing_id uuid references listings(id) on delete cascade, external_id text, external_url text, status text, last_sync_at timestamptz, unique(channel_id,listing_id));
create table plans(id uuid primary key default gen_random_uuid(), code text unique not null, name text not null, monthly_price numeric(10,2), stripe_price_id text, active boolean default true);
create table subscriptions(id uuid primary key default gen_random_uuid(), company_id uuid references companies(id), plan_id uuid references plans(id), provider text, provider_subscription_id text, status text, trial_ends_at timestamptz, current_period_end timestamptz);
create table analytics_events(id bigserial primary key, profile_id uuid, company_id uuid, listing_id uuid, event text not null, properties jsonb default '{}'::jsonb, created_at timestamptz default now());
create index listings_search_idx on listings using gin(to_tsvector('italian', coalesce(title,'')||' '||coalesce(description,'')));
create index listings_company_idx on listings(company_id,status);
create index offers_seller_idx on offers(seller_company_id,status);
-- RLS policies must be enabled and tailored before production launch.
